services:
  postgres:
    image: postgres:17          # o 18 si ya está estable
    environment:
      POSTGRES_DB: manuales
      POSTGRES_USER: manuales
      POSTGRES_PASSWORD: cambiame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manuales -d manuales"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: