CREATE TABLE asignatura (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(150) NOT NULL,
    siglas       VARCHAR(10)  NOT NULL UNIQUE,
    curso        INTEGER      NOT NULL CHECK (curso BETWEEN 1 AND 4),
    cuatrimestre INTEGER      CHECK (cuatrimestre IN (1, 2))
);