CREATE TABLE documento (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             VARCHAR(255) NOT NULL,
    nombre_fichero     VARCHAR(255) NOT NULL,
    tema               VARCHAR(150),
    source_id          VARCHAR(255) NOT NULL UNIQUE,
    estado_indexacion  VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    fecha_subida       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    asignatura_id      BIGINT       NOT NULL REFERENCES asignatura(id)
);

CREATE INDEX idx_documento_asignatura ON documento(asignatura_id);